name: kralupy_streets
description: Ulicze is a quiz app where users test their knowledge of streets in Kralupy nad Vltavou.
publish_to: 'none'
version: 1.2.0+7

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.3
  firebase_analytics: ^10.5.1
  firebase_core: ^2.17.0
  firebase_messaging: ^14.7.4
  firebase_storage: ^11.2.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_onboarding_slider: ^1.0.11
  flutter_riverpod: ^2.4.4
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  image_picker: ^1.0.4
  location: ^5.0.3
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'

flutter_launcher_icons:
  image_path_android: "assets/images/app_icon_complete.png"
  image_path_ios: "assets/images/app_icon_complete.png"
  android: true
  ios: true
  adaptive_icon_background: "#c41b0e"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#c41b0e"
